const {chromium}=require('playwright');
(async()=>{
  const browser=await chromium.launch({...(process.env.QA_BROWSER_EXECUTABLE?{executablePath:process.env.QA_BROWSER_EXECUTABLE}:{}),headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(process.env.QA_BASE_URL || 'http://127.0.0.1:8765');
  await page.locator('#cards .card').first().waitFor();
  await page.screenshot({path:'data/workspace-preview.png',fullPage:true});
  await page.getByRole('link',{name:'会话分析',exact:false}).click();
  await page.locator('#list [data-open="C001"]').click();
  await page.getByRole('button',{name:'驳回风险',exact:true}).click();
  await page.locator('.dialog-feedback').filter({hasText:'修改或驳回时请填写原因'}).waitFor();
  await page.getByRole('button',{name:'确认方案',exact:true}).click();
  await page.getByRole('button',{name:'登记开始执行',exact:true}).waitFor();
  await page.getByRole('button',{name:'登记开始执行',exact:true}).click();
  await page.locator('#resolution').fill('已核实订单并同步物流进度，用户确认问题解决。');
  await page.locator('#feedback').selectOption('satisfied');
  await page.getByRole('button',{name:'登记结果并结案',exact:true}).click();
  await page.getByRole('button',{name:'沉淀为案例草稿',exact:true}).waitFor();
  await page.getByRole('button',{name:'沉淀为案例草稿',exact:true}).click();
  await page.locator('#detail .dialog-feedback').filter({hasText:'知识草稿'}).waitFor();
  await page.getByRole('button',{name:'关闭详情',exact:true}).click();
  await page.getByRole('link',{name:'企业知识库',exact:false}).click();
  await page.locator('[data-edit-knowledge="CASE-C001"]').click();
  await page.locator('#knowledge-form input[name="title"]').fill('已复盘的承诺边界案例');
  await page.getByRole('button',{name:'保存为草稿',exact:true}).click();
  await page.locator('#knowledge-dialog').waitFor({state:'hidden'});
  await page.locator('[data-publish="CASE-C001"]').click();
  await page.locator('.knowledge-card').filter({hasText:'已复盘的承诺边界案例'}).getByText('已发布',{exact:true}).waitFor();
  await page.getByRole('link',{name:'数据复盘',exact:false}).click();
  await page.locator('#insight-cards').getByText('16.7%',{exact:true}).waitFor();
  await page.reload();
  await page.locator('#insight-cards').getByText('16.7%',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('link',{name:'主管总览',exact:false}).click();
  await page.screenshot({path:'data/mobile-preview.png',fullPage:true});
  const layout=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth}));
  if(layout.width>layout.viewport)errors.push('Mobile overflow: '+JSON.stringify(layout));
  console.log(JSON.stringify({success:errors.length===0,errors,checks:['overview rendering','visible validation error','approve/start/resolve','case edit and publish','feedback metrics','reload persistence','mobile layout']}));
  await browser.close();
  if(errors.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exit(1)});
